# Generated by Django 6.0.6 on 2026-08-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Craft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("craft_name", models.CharField(max_length=125, unique=True)),
            ],
            options={
                "verbose_name": "craft",
                "verbose_name_plural": "crafts",
                "db_table": "crafts",
            },
        ),
    ]
