# Generated by Django 6.0.6 on 2026-08-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_is_phone_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artisanprofile",
            name="craft",
        ),
        migrations.RemoveField(
            model_name="artisanprofile",
            name="region",
        ),
        migrations.DeleteModel(
            name="Craft",
        ),
        migrations.DeleteModel(
            name="Region",
        ),
    ]
