# Generated by Django 6.0.6 on 2026-08-27 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("craft", "0001_initial"),
        ("region", "0001_initial"),
        ("users", "0003_remove_artisanprofile_craft_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artisanprofile",
            name="craft",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artisans",
                to="craft.craft",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artisanprofile",
            name="region",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artisans",
                to="region.region",
            ),
            preserve_default=False,
        ),
    ]
